use_frameworks!

platform :ios, '13.0'

target 'FieldNoteIcons_Example' do
  pod 'FieldNoteIcons', :path => '../'
#  pod 'AZSClient'

  target 'FieldNoteIcons_Tests' do
    inherit! :search_paths

  end
end
